### PR TITLE
A new daemon is always started on Java 8 

### LINKED ISSUE #260: No reuse of daemons - error on daemon creation - unknown signal TSTP (Windows 10, Bellsoft Liberica JDK)
When running mvnd commands under windows with Bellsoft Liberica JDK, mvnd always creates a new daemon - the old ones are shown as "incompatible" or "stopped". The daemon log file shows an error `Unknown signal: TSTP` on creation of `org.mvndaemon.mvnd.daemon.Server`.

Note: it works f.i. with "Java version: 1.8.0_161, vendor: Oracle Corporation", so perhaps it's only the non-Oracle (OpenJDK?) ones, that don't work.

Test commands:
```
> mvnd --version
mvnd native client 0.1.1-windows-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files (noinst)\javautil\mvnd\mvn
Java version: 1.8.0_202, vendor: BellSoft, runtime: C:\Program Files\Java\jdk8u202 (Liberica)\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> mvnd --version
mvnd native client 0.1.1-windows-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files (noinst)\javautil\mvnd\mvn
Java version: 1.8.0_202, vendor: BellSoft, runtime: C:\Program Files\Java\jdk8u202 (Liberica)\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> mvnd --status
                                    UUID      PID   Port   Status    RSS            Last activity  Java home
    9aa84b9f-9eac-48d1-9829-5d77e8dc161f     9388  58319     Idle   102m  2020-12-13T21:49:03.669  C:\Program Files\Java\jdk8u202 (Liberica)\jre
    4ad65c3c-77fd-48ea-9778-8488d03916b0    18012  58313     Idle   102m  2020-12-13T21:48:53.691  C:\Program Files\Java\jdk8u202 (Liberica)\jre
```
StackTrace:
```
==> %userprofile%\.m2\mvnd\registry\0.1.1\daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log <==
21:48:51.319 W Unable to ignore INT and TSTP signals
java.lang.IllegalArgumentException: Unknown signal: TSTP
        at sun.misc.Signal.<init>(Signal.java:143)
        at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:105)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:75)
```

[registry.zip](https://github.com/mvndaemon/mvnd/files/5685423/registry.zip)
[daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log](https://github.com/mvndaemon/mvnd/files/5685424/daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log)
[daemon-9aa84b9f-9eac-48d1-9829-5d77e8dc161f.log](https://github.com/mvndaemon/mvnd/files/5685425/daemon-9aa84b9f-9eac-48d1-9829-5d77e8dc161f.log)

### LINKED ISSUE #261: No reuse of daemons, no build speedup.
'Starting new daemon, 1 incompatible, 3 stopped'

Each time I invoke mvnd, it starts a new daemon, and there is no build speedup.  How does it check for a compatible daemon?

OS: Ubuntu 20.04
AMD Ryzen Processor
Oracle 1.8.0 JDK

> mvnd --version
mvnd native client 0.1.1-linux-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/***/mvnd-0.1.1-linux-amd64/mvn
Java version: 1.8.0_***, vendor: Oracle Corporation, runtime: ***
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-53-generic", arch: "amd64", family: "unix"

P.S. I would use mvnd even with no speedup because the build output is so improved!

### LINKED ISSUE #266: A new daemon is always started with OpenJDK 8
Hi,

Is there a known issue with Java versions lower than 11 ?

With Open JDK 8 I always obtain the following message :

```
$mvnd --version
Starting new daemon, X incompatible and Y stopped daemons could not be reused, ...
```

This furtive message doesn't appear with open JDK 11.

Reproduced on Windows 10 (mvnd-0.1.1-windows-amd64) & Linux Centos 7 or Ubuntu 20.04 (mvnd-0.1.1-linux-amd64).

First lines of log in Centos 7 :

```
11:51:38.662 D Initializing daemon with properties:
     mvnd.noDaemon=false
     mvnd.debug=false
     mvnd.idleTimeout=3h
     mvnd.keepAlive=100ms
     mvnd.extClasspath=
     mvnd.coreExtensions=
     mvnd.minHeapSize=128M
     mvnd.maxHeapSize=2G
     mvnd.jvmArgs=
     mvnd.enableAssertions=false
     mvnd.expirationCheckDelay=10s
     mvnd.duplicateDaemonGracePeriod=10s

11:51:38.667 I Daemon started
11:51:38.669 D daemon is running. Sleeping until state changes.
11:51:38.694 I Client connected
11:51:38.698 I Waiting for request
11:51:38.702 I Request received: [...]
```

in Windows 10 :

```
09:45:34.813 W Unable to ignore INT and TSTP signals
java.lang.IllegalArgumentException: Unknown signal: TSTP
	at java.base/jdk.internal.misc.Signal.<init>(Signal.java:148)
	at jdk.unsupported/sun.misc.Signal.<init>(Signal.java:139)
	at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:105)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:75)
09:45:35.906 D Initializing daemon with properties:
     mvnd.noDaemon=false
     mvnd.debug=false
     mvnd.idleTimeout=3h
     mvnd.keepAlive=100ms
     mvnd.extClasspath=
     mvnd.coreExtensions=
     mvnd.minHeapSize=128M
     mvnd.maxHeapSize=2G
     mvnd.jvmArgs=
     mvnd.enableAssertions=false
     mvnd.expirationCheckDelay=10s
     mvnd.duplicateDaemonGracePeriod=10s

09:45:35.914 I Daemon started
09:45:35.915 D daemon is running. Sleeping until state changes.
09:45:36.018 I Client connected
09:45:36.741 I Waiting for request
09:45:36.746 I Request received: [...]
```

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #266 
Fix #260 
Fix #261

### CODE REVIEW

File: common/src/main/java/org/mvndaemon/mvnd/common/Environment.java [hunk 1]
```diff
@@ -224,7 +224,13 @@
     /**
      * Internal property to tell the daemon the width of the terminal
      */
-    MVND_TERMINAL_WIDTH("mvnd.terminalWidth", null, 0, OptionType.INTEGER, Flags.INTERNAL);
+    MVND_TERMINAL_WIDTH("mvnd.terminalWidth", null, 0, OptionType.INTEGER, Flags.INTERNAL),
+    /**
+     * Internal property to tell the daemon which JAVA_HOME was used to start it. It needs to be passed explicitly
+     * because the value may differ from what the daemon sees through <code>System.getProperty("java.home")</code>.
+     */
+    MVND_JAVA_HOME("mvnd.java.home", null, null, OptionType.PATH, Flags.INTERNAL);
```
Comment (gnodet) [inline common/src/main/java/org/mvndaemon/mvnd/common/Environment.java:232]: Could you remove the duplicate semicolon ?

Comment (ppalaga) [reply common/src/main/java/org/mvndaemon/mvnd/common/Environment.java:232]: How could I put it there?!?! :)

Comment (ppalaga) [reply common/src/main/java/org/mvndaemon/mvnd/common/Environment.java:232]: Anything else?
